allow termination of script on first error

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Fail on the first error
+set -e
+
 echo "
 ================================================
 
